//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeaceHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogReply
    {
        public int replyId { get; set; }
        public int blogId { get; set; }
        public int userId { get; set; }
        public string replyComment { get; set; }
    
        public virtual Blog Blog { get; set; }
        public virtual User User { get; set; }
    }
}
