//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeaceHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class savedRoom
    {
        public int savedRoomId { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> roomId { get; set; }
        public Nullable<int> totalSaved { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual User User { get; set; }
    }
}
